### ISSUE TITLE
Authentication callbacks

### ISSUE THREAD

**Issue by n0daft** [ElderByte-/angular-warden-oauth-client#1]
Extend Auth provider to accept some callbacks in its config. This way we could execute some code right after successful authentication.

**Use Case**
Assuming that after a successful user login some code has to be executed which relies on the Principal data. It has to be executed:

* right after authentication
* always after authentication

For this an authenticate callback could be defined.  See PR #2

**Suggestion**
```javascript
 AuthProvider.config({
            clientId : 'someClient',
            loginState : 'login',
            authSuccessCallback : function () {
               var someService = angular.injector().get('SomeService');
               var principal = angular.injector().get('Principal');
               someService.doSomething(principal.getIdentity().login)
            },
            defaultRedirectState : 'redirectState',
            stateRoleSecurityEnabled : true
        });
```

**Comment by n0daft** [comment]
@IsNull what's your opinion? I'm not sure about the injector getting the service instances. Maybe you have another idea.

**Comment by IsNull** [comment]
PR has been merged.
